### ISSUE TITLE
Lambda python 3.10 tracing (and other concerns)

### ISSUE THREAD

**Issue by 0x73746F66** [lumigo-io/python_tracer#276]
A genuine ticket intended to raise awareness and engage in good faith

## First impression

Great onboarding

Well maybe in the past.. it does not have any tracing unless I am using older runtimes..

The cloudformation stack seems to auto-magically trace python3.9 runtime without a layer, this is good, I am glad it was designed this way originally - but it seems to have broken and the docs do not have any indication it's broken or how to onboard to Lumigo with a suitable replacement that works.

## No support for current runtimes

So Lumigo is supposed to be entirely focused on AWS Lambda, right?

Given python3.10 for Lambda has been out for quite a while now, and python3.11 containers were recently added too - should we expect tracing to start working again for the current versions of Lambda?

Or should customers expect to go through Lumigo off-boarding to clean up their accounts of Lumigo resources first, and then start fresh with a new onboarding (that has not been documented yet) to get the current runtimes traceable the same way the old one were, or something else?

## No support for Lambda features announced years ago

I started using LambdaURL (for only 1 Lamdba function ARN) and it blew up the Lumigo dashboard with a Lambda 'instance' for every URL, which is millions of URL paths from unique combinations corresponding to a small database with 10's of users data (not thousands of users) - LambdaURL may not be very widely used in the customer base but I doubt after these couple of years since it went GA I am the first. The dashboard is the entire product, being unusable is a self-imposed Denial of Service- the support contact was advised and the scheduled call ccommitment with _technical people_ was never arranged for the agreed date//time (probably being and Australian makes it too hard, as usual)

## Lacking support for flagship Lambda features

Also the manual tracing via the Lambda layer runtimes are now 4 major releases behind, many years now,

## Conclusions

I'm trying to be fair but from a user's perspective I can only logically assume Lumigo is not well funded or not staffed in the development team appropriately for maintaining years old Lambda features, or fixing critical product breaking bugs with features released years ago.

That's based on Lumigo being a commercial offering that has observably fallen this far behind with business-as-usual (BAU) software development efforts, and when the product's only focus is such a _tiny niche_ of a serverless world that is also a _tiny niche_ of cloud computing, and cloud itself is not the dominant considering mobile app, desktop software, and on-prem. When the niche in a niche in a niche that is AWS Lambda is your core focus - it would be acceptable, and expected, of an MIT/BSD licensed (full open source) project - but not a paid commercial offering.

I'm not sure a paid commercial product like Lumigo has a future if it remains this far behind - maybe going open source with the caveat it's already falling out of current supported Lambdas

I hope this thread is taken constructively and encourages a productive conversation to assure customers or provide an alternative like going fully open source

**Comment by mmanciop** [comment]
Hi @0x73746F66,

I am the product manager at Lumigo for all things distributed tracing. I can assure you that your worries about "Lumigo abandoning Lambda" are far from reality.

As all startups, there are some prioritization decisions that we perform regularly about "what to do next". We keep a close eye on the telemetry that Lumigo itself collects, and the reason why we have not enabled autotrace for Python 3.10, is that it has not been picked up by virtually any user out there. The lion's share of Python Lambda's is on 3.9, with 3.8, 3.7, 3.6 forming a long tail.

**Comment by chrisdlangton** [comment]
Consider i rolled back to 3.9 because of the lack of tracing

Odd to get a response like that from a observability product, the product owner no less

Correlation is far from causation
And absence of data os not absence of customer demand

**Comment by mmanciop** [comment]
Unfortunately my answer got sent too soon, finger slip. I acknowledge the possibility of a selection bias and/or a survivor bias, so far you are my first datapoint, thank you for that :-)

**Comment by chrisdlangton** [comment]
Wow another one
It's like the old saying, we're perfectly secure because noone has ever looked at our security or complained about it

Do you really believe that I am just 1 data point because "not looking" is totally the point you just made as though it's a positive..

It might have been more appropriate to remain open minded and perhaps consider if one new user noticed it immediately that many customers that aren't new just put up with it as "normal Lumigo" silently

New user's are typically going to be way more interactive that the those silently going about things as they always have, waiting patiently for things to change

**Comment by mmanciop** [comment]
Oh, I am grateful for your feedback, and it is taken in due consideration. For example, I immediately went and double checked, which confirmed what I said about manual tracing:

<img width="1727" alt="Screenshot 2023-04-21 at 12 48 25" src="https://user-images.githubusercontent.com/14020598/233618218-59a6ee41-f61e-4fb6-87eb-27414bf486af.png">

I also found a small bug in our CDK constructs, [already fixed](https://github.com/lumigo-io/lumigo-cdk-constructs/commit/2f808dd89ccfb73b0a8be858de758f82cdcf6fb4), where I had to adjust the way we check for the Lambda function runtime, given that the minimum version of CDK supported did not yet have Python 3.10, which has been released three days ago (April 18, 2023): https://aws.amazon.com/blogs/compute/python-3-10-runtime-now-available-in-aws-lambda/.

Besides, I am not quite sure why you seem to think I am brushing your feedback away, or why this conversation seems to have such an adversarial tone, but as I said repeatedly, I am thankful for the useful feedback.

**Comment by chrisdlangton** [comment]
Do you mean updated 3 days ago, or just announced, or perhaps the classic lambda deployment, i cant see what you're cherry picking there

I just checked and we were using 3.10 in code build as far back as July last year, not sure when lambda ECR landed but I see I first built 3.10 from the official ECR in March, i.e. using Lambda deployment with the official Lambda container in ECR

Before that it appears to be 3.10 from yun repo in a amazonlinux base in ECR and custom Lambda runtime

Anyways im too terse in chat, id love to grab a time in calendar next week once my team yace had a chance to look at putting tracing in code directly

Cheers for the attention to detail, hopefully the rest of that feedback we didn't deep dive into also holds some value

**Comment by chrisdlangton** [comment]
Re: tracing lambda 3.10

Manual tracing code that works for 3.9 , verified in the Lumigo dashboard, stops tracing (verbose) and reporting as soon as you redeploy to 3.10 runtime

So it is confirmed, tracing never worked for 3.10 these past 9 months since AWS first released it in official repos (and never worked for python 3.10 via custom runtimes would be assumed problematic too)

**Comment by mmanciop** [comment]
I showed above that it does work for 3.10 when using the `python3.10` runtime. Show me what you did and what the error is, and I will be happy to sort it out.

**Comment by chrisdlangton** [comment]
@mmanciop it shows log ingestion and visualisation of the logs, not that the invocation was traced

Where are tracking errors shown? The dashboard literally has just an indicator that is grey for not tracing and blue when it is enabled. The error is generic telling me that I need to use one of the supported languages or try manual tracing....

Doing manual tracing cannot be tested locally because the tracer source code short circuits if not running in an AWS Lambda environment, and when it is running the 8nky log I've ever seen output to cloud watch was when I didn't give it a valid token, otherwise the tracer is silent

**Comment by chrisdlangton** [comment]
@mmanciop it shows log ingestion and visualisation of the logs, not that the invocation was traced

Where are tracking errors shown? The dashboard literally has just an indicator that is grey for not tracing and blue when it is enabled. The error is generic telling me that I need to use one of the supported languages or try manual tracing....

Doing manual tracing cannot be tested locally because the tracer source code short circuits if not running in an AWS Lambda environment, and when it is running the 8nky log I've ever seen output to cloud watch was when I didn't give it a valid token, otherwise the tracer is silent ![Screenshot_20230428-002136.png](https://user-images.githubusercontent.com/3494633/234891691-b3f89d07-d837-47d3-a4da-dcf9c01a8eed.png)

**Comment by chrisdlangton** [comment]
![Screenshot_20230428-002943.png](https://user-images.githubusercontent.com/3494633/234894943-c7217129-97fa-4131-80c5-71b22ee86975.png)

**Comment by mmanciop** [comment]
> @mmanciop your screenshot? No, it shows log ingestion and visualisation of the logs, not that the invocation was traced

Not true: the event and return value are in Lumigo **only** if the invocation has been **traced**.

> The dashboard has just an indicator that is grey for not tracing and blue when it is enabled. The error is generic telling me that I need to use one of the supported languages or try manual tracing....

For autotracing, this is true. Enabling it for the `python3.10` runtime is very high on our TODO list, but we do not currently support injecting Lambda tracers in any provided runtime (including Docker in Lambda), so that won't help you I think.

> Doing manual tracing cannot be tested locally because the tracer source code short circuits if not running in an AWS Lambda environment, and when it is running the only log I've ever seen output to CloudWatch was when I didn't give it a valid token, otherwise the tracer is silent even when using the verbose argument

Would you please set on your Lambda function the `LUMIGO_DEBUG=true` environment variable and see what it says in the logs? I need that debug output to help you further.

**Comment by 0x73746F66** [comment]
Are you sure that is the correct Env var?? It is not in the source code for 3.10
![image](https://user-images.githubusercontent.com/93355168/235009798-c6f2fea7-88ff-420a-b503-759760ae217b.png)

I think you mean `LUMIGO_VERBOSE` and I already shared i've configured that and asked where I might actually see some output from that as the places I know of and described all show nothing

**Comment by 0x73746F66** [comment]
Keeping open until `python3.10` is autotraced

**Comment by mmanciop** [comment]
`LUMIGO_DEBUG` is implemented in the [`python-core`](https://github.com/lumigo-io/python-core/blob/cab38f366b723361632db303e9efec1808f021e4/src/lumigo_core/logger.py#L11) repo, which is [a dependency](https://github.com/lumigo-io/python_tracer/blob/be1d6c852ddcc0e0e696da9832cdb1ad7400876b/setup.py#L17) to `python_tracer`.

You issue seems somehow an activation one (tracer not turning on), but we can be sure only when looking at the debug output (or lack thereof).

**Comment by mmanciop** [comment]
@chrisdlangton any chance of getting the debug output? I just saw a very similar bug report from a different user, and I would like to make sure it's the same issue.

**Comment by chrisdlangton** [comment]
Yeah I got that working but won't provide the output as it contains sensitive data (including the token) and is quite a lot of text

What are you looking for exactly?

It generally reports `successful reporting, code: 200` after a log entry with a JSON blob

This shows trace id and that it see's it is python3.10 - but checking the lumigo dashboard for the past hour the only invocations are the ones that included the `LUMIGO_DEBUG=true` and yet it has `Function untraced` as seen in my previous screenshots

**Comment by mmanciop** [comment]
The "Function untraced" is happening because what you did with LUMIGO_VERBOSE is preventing the event from reaching Lumigo, and (with an oversimplification on our end due to architecture), if we see an invocation without event, we considering untraced.

**Comment by chrisdlangton** [comment]
So what you're saying is, this task you gave me takes me no closer to understanding how to complete onboarding to the main feature

**Comment by mmanciop** [comment]
Autotrace for Python 3.10 is GA: https://announcekit.co/lumigo/release-notes/lambda-python-3.10-runtime-supported-6UqwU

**Comment by mmanciop** [comment]
> So what you're saying is, this task you gave me takes me no closer to understanding how to complete onboarding to the main feature

No, what I am saying is that unless you show me that data, I cannot help you further. And the data sharing does not have to be on GitHub; rather, if you want further help, please provide them through a ticket in Lumigo's support portal: https://support.lumigo.io/hc/en-gb.

Since the other points you raised are noted, but do not concern this tracer specifically, I am going ahead and closing this issue. Thanks for reporting :-)
